// starport-agent（节点侧）↔ starport-panel（控制面）契约，唯一事实来源。
//
// 拓扑（Nacos 2.x 风格）：agent 主动呼出、单条 gRPC 双向流长连；面板沿同一条流反向下发指令。
// 节点上不监听端口、不保管 SSH 凭证，天然穿 NAT。
//
//   1. 引导注册走 HTTP：POST {panel}/api/v1/agents/register（凭引导令牌），
//      应答里下发 nodeId / agentToken / grpcEndpoints；agent 据此连 gRPC 端口。
//   2. 长连：NodeAgentService.Connect 双向流。metadata 携带
//        x-starport-agent-token / x-starport-node-id / x-starport-agent-version
//      令牌无效返回 UNAUTHENTICATED，agent 清本地身份重新注册。
//
// 生成物：internal/pb/agentv1（`make proto` / `buf generate`，产物入库）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 节点角色。
type NodeRole int32

const (
	NodeRole_NODE_ROLE_UNSPECIFIED  NodeRole = 0
	NodeRole_NODE_ROLE_FIRST_MASTER NodeRole = 1 // kubeadm init --upload-certs
	NodeRole_NODE_ROLE_JOIN_MASTER  NodeRole = 2 // join --control-plane --certificate-key
	NodeRole_NODE_ROLE_WORKER       NodeRole = 3 // join
)

// Enum value maps for NodeRole.
var (
	NodeRole_name = map[int32]string{
		0: "NODE_ROLE_UNSPECIFIED",
		1: "NODE_ROLE_FIRST_MASTER",
		2: "NODE_ROLE_JOIN_MASTER",
		3: "NODE_ROLE_WORKER",
	}
	NodeRole_value = map[string]int32{
		"NODE_ROLE_UNSPECIFIED":  0,
		"NODE_ROLE_FIRST_MASTER": 1,
		"NODE_ROLE_JOIN_MASTER":  2,
		"NODE_ROLE_WORKER":       3,
	}
)

func (x NodeRole) Enum() *NodeRole {
	p := new(NodeRole)
	*p = x
	return p
}

func (x NodeRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeRole) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (NodeRole) Type() protoreflect.EnumType {
	return &file_agent_v1_agent_proto_enumTypes[0]
}

func (x NodeRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeRole.Descriptor instead.
func (NodeRole) EnumDescriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

// CNI 类型。
type CniType int32

const (
	CniType_CNI_TYPE_UNSPECIFIED CniType = 0
	CniType_CNI_TYPE_CILIUM      CniType = 1
	CniType_CNI_TYPE_CALICO      CniType = 2
)

// Enum value maps for CniType.
var (
	CniType_name = map[int32]string{
		0: "CNI_TYPE_UNSPECIFIED",
		1: "CNI_TYPE_CILIUM",
		2: "CNI_TYPE_CALICO",
	}
	CniType_value = map[string]int32{
		"CNI_TYPE_UNSPECIFIED": 0,
		"CNI_TYPE_CILIUM":      1,
		"CNI_TYPE_CALICO":      2,
	}
)

func (x CniType) Enum() *CniType {
	p := new(CniType)
	*p = x
	return p
}

func (x CniType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CniType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_v1_agent_proto_enumTypes[1].Descriptor()
}

func (CniType) Type() protoreflect.EnumType {
	return &file_agent_v1_agent_proto_enumTypes[1]
}

func (x CniType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CniType.Descriptor instead.
func (CniType) EnumDescriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

// 制品来源。
type ArtifactMode int32

const (
	ArtifactMode_ARTIFACT_MODE_UNSPECIFIED ArtifactMode = 0
	ArtifactMode_ARTIFACT_MODE_BUNDLE      ArtifactMode = 1 // 离线包：节点无需外网
	ArtifactMode_ARTIFACT_MODE_ONLINE      ArtifactMode = 2 // 在线：apt + 镜像仓，仅 calico
)

// Enum value maps for ArtifactMode.
var (
	ArtifactMode_name = map[int32]string{
		0: "ARTIFACT_MODE_UNSPECIFIED",
		1: "ARTIFACT_MODE_BUNDLE",
		2: "ARTIFACT_MODE_ONLINE",
	}
	ArtifactMode_value = map[string]int32{
		"ARTIFACT_MODE_UNSPECIFIED": 0,
		"ARTIFACT_MODE_BUNDLE":      1,
		"ARTIFACT_MODE_ONLINE":      2,
	}
)

func (x ArtifactMode) Enum() *ArtifactMode {
	p := new(ArtifactMode)
	*p = x
	return p
}

func (x ArtifactMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArtifactMode) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_v1_agent_proto_enumTypes[2].Descriptor()
}

func (ArtifactMode) Type() protoreflect.EnumType {
	return &file_agent_v1_agent_proto_enumTypes[2]
}

func (x ArtifactMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArtifactMode.Descriptor instead.
func (ArtifactMode) EnumDescriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

// 控制面 → agent。
type ServerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 关联 ID：exec/install/cancel 与 session_* 用；ping 留空。
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*ServerFrame_Exec
	//	*ServerFrame_Install
	//	*ServerFrame_Cancel
	//	*ServerFrame_Ping
	//	*ServerFrame_SessionOpen
	//	*ServerFrame_SessionStdin
	//	*ServerFrame_SessionResize
	//	*ServerFrame_SessionClose
	Body          isServerFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ServerFrame) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ServerFrame) GetBody() isServerFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServerFrame) GetExec() *ExecRequest {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Exec); ok {
			return x.Exec
		}
	}
	return nil
}

func (x *ServerFrame) GetInstall() *InstallRequest {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Install); ok {
			return x.Install
		}
	}
	return nil
}

func (x *ServerFrame) GetCancel() *CancelRequest {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *ServerFrame) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *ServerFrame) GetSessionOpen() *SessionOpen {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_SessionOpen); ok {
			return x.SessionOpen
		}
	}
	return nil
}

func (x *ServerFrame) GetSessionStdin() *SessionStdin {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_SessionStdin); ok {
			return x.SessionStdin
		}
	}
	return nil
}

func (x *ServerFrame) GetSessionResize() *SessionResize {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_SessionResize); ok {
			return x.SessionResize
		}
	}
	return nil
}

func (x *ServerFrame) GetSessionClose() *SessionClose {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_SessionClose); ok {
			return x.SessionClose
		}
	}
	return nil
}

type isServerFrame_Body interface {
	isServerFrame_Body()
}

type ServerFrame_Exec struct {
	Exec *ExecRequest `protobuf:"bytes,10,opt,name=exec,proto3,oneof"`
}

type ServerFrame_Install struct {
	Install *InstallRequest `protobuf:"bytes,11,opt,name=install,proto3,oneof"`
}

type ServerFrame_Cancel struct {
	Cancel *CancelRequest `protobuf:"bytes,12,opt,name=cancel,proto3,oneof"`
}

type ServerFrame_Ping struct {
	Ping *Ping `protobuf:"bytes,13,opt,name=ping,proto3,oneof"`
}

type ServerFrame_SessionOpen struct {
	SessionOpen *SessionOpen `protobuf:"bytes,20,opt,name=session_open,json=sessionOpen,proto3,oneof"`
}

type ServerFrame_SessionStdin struct {
	SessionStdin *SessionStdin `protobuf:"bytes,21,opt,name=session_stdin,json=sessionStdin,proto3,oneof"`
}

type ServerFrame_SessionResize struct {
	SessionResize *SessionResize `protobuf:"bytes,22,opt,name=session_resize,json=sessionResize,proto3,oneof"`
}

type ServerFrame_SessionClose struct {
	SessionClose *SessionClose `protobuf:"bytes,23,opt,name=session_close,json=sessionClose,proto3,oneof"`
}

func (*ServerFrame_Exec) isServerFrame_Body() {}

func (*ServerFrame_Install) isServerFrame_Body() {}

func (*ServerFrame_Cancel) isServerFrame_Body() {}

func (*ServerFrame_Ping) isServerFrame_Body() {}

func (*ServerFrame_SessionOpen) isServerFrame_Body() {}

func (*ServerFrame_SessionStdin) isServerFrame_Body() {}

func (*ServerFrame_SessionResize) isServerFrame_Body() {}

func (*ServerFrame_SessionClose) isServerFrame_Body() {}

// agent → 控制面。
type AgentFrame struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*AgentFrame_Ready
	//	*AgentFrame_Heartbeat
	//	*AgentFrame_Log
	//	*AgentFrame_Result
	//	*AgentFrame_Pong
	//	*AgentFrame_SessionData
	//	*AgentFrame_SessionExit
	Body          isAgentFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentFrame) Reset() {
	*x = AgentFrame{}
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentFrame) ProtoMessage() {}

func (x *AgentFrame) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentFrame.ProtoReflect.Descriptor instead.
func (*AgentFrame) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentFrame) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AgentFrame) GetBody() isAgentFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *AgentFrame) GetReady() *Ready {
	if x != nil {
		if x, ok := x.Body.(*AgentFrame_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *AgentFrame) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Body.(*AgentFrame_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentFrame) GetLog() *LogLine {
	if x != nil {
		if x, ok := x.Body.(*AgentFrame_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *AgentFrame) GetResult() *ExecResult {
	if x != nil {
		if x, ok := x.Body.(*AgentFrame_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *AgentFrame) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Body.(*AgentFrame_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *AgentFrame) GetSessionData() *SessionData {
	if x != nil {
		if x, ok := x.Body.(*AgentFrame_SessionData); ok {
			return x.SessionData
		}
	}
	return nil
}

func (x *AgentFrame) GetSessionExit() *SessionExit {
	if x != nil {
		if x, ok := x.Body.(*AgentFrame_SessionExit); ok {
			return x.SessionExit
		}
	}
	return nil
}

type isAgentFrame_Body interface {
	isAgentFrame_Body()
}

type AgentFrame_Ready struct {
	Ready *Ready `protobuf:"bytes,10,opt,name=ready,proto3,oneof"`
}

type AgentFrame_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,11,opt,name=heartbeat,proto3,oneof"`
}

type AgentFrame_Log struct {
	Log *LogLine `protobuf:"bytes,12,opt,name=log,proto3,oneof"`
}

type AgentFrame_Result struct {
	Result *ExecResult `protobuf:"bytes,13,opt,name=result,proto3,oneof"`
}

type AgentFrame_Pong struct {
	Pong *Pong `protobuf:"bytes,14,opt,name=pong,proto3,oneof"`
}

type AgentFrame_SessionData struct {
	SessionData *SessionData `protobuf:"bytes,20,opt,name=session_data,json=sessionData,proto3,oneof"`
}

type AgentFrame_SessionExit struct {
	SessionExit *SessionExit `protobuf:"bytes,21,opt,name=session_exit,json=sessionExit,proto3,oneof"`
}

func (*AgentFrame_Ready) isAgentFrame_Body() {}

func (*AgentFrame_Heartbeat) isAgentFrame_Body() {}

func (*AgentFrame_Log) isAgentFrame_Body() {}

func (*AgentFrame_Result) isAgentFrame_Body() {}

func (*AgentFrame_Pong) isAgentFrame_Body() {}

func (*AgentFrame_SessionData) isAgentFrame_Body() {}

func (*AgentFrame_SessionExit) isAgentFrame_Body() {}

// 下发脚本，本机 shell 执行（串行队列）。
type ExecRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Script string                 `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
	// 到点强杀；<=0 用 agent 默认（30 分钟）。
	TimeoutMs     int64 `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ExecRequest) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *ExecRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// 下发内置 K8s 装机（结构化，非脚本）。无外部超时，仅支持 cancel。
type InstallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *InstallSpec           `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallRequest) Reset() {
	*x = InstallRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallRequest) ProtoMessage() {}

func (x *InstallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallRequest.ProtoReflect.Descriptor instead.
func (*InstallRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *InstallRequest) GetSpec() *InstallSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// 取消 request_id 对应的 exec / install（杀整进程组）。
type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

// 应用层探活。
type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

// 开一条流式/交互会话（网页终端、kubectl logs -f）。与 exec 不共用执行通道。
type SessionOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Script        string                 `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
	Tty           bool                   `protobuf:"varint,2,opt,name=tty,proto3" json:"tty,omitempty"`
	Cols          int32                  `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          int32                  `protobuf:"varint,4,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionOpen) Reset() {
	*x = SessionOpen{}
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionOpen) ProtoMessage() {}

func (x *SessionOpen) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionOpen.ProtoReflect.Descriptor instead.
func (*SessionOpen) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *SessionOpen) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *SessionOpen) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

func (x *SessionOpen) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *SessionOpen) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type SessionStdin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStdin) Reset() {
	*x = SessionStdin{}
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStdin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStdin) ProtoMessage() {}

func (x *SessionStdin) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStdin.ProtoReflect.Descriptor instead.
func (*SessionStdin) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *SessionStdin) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SessionResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          int32                  `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          int32                  `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionResize) Reset() {
	*x = SessionResize{}
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResize) ProtoMessage() {}

func (x *SessionResize) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResize.ProtoReflect.Descriptor instead.
func (*SessionResize) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *SessionResize) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *SessionResize) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type SessionClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionClose) Reset() {
	*x = SessionClose{}
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionClose) ProtoMessage() {}

func (x *SessionClose) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionClose.ProtoReflect.Descriptor instead.
func (*SessionClose) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

// 连接建立后首帧：身份 + 现状。
type Ready struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint64                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Facts         *Facts                 `protobuf:"bytes,3,opt,name=facts,proto3" json:"facts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ready) Reset() {
	*x = Ready{}
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ready) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ready) ProtoMessage() {}

func (x *Ready) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ready.ProtoReflect.Descriptor instead.
func (*Ready) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *Ready) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *Ready) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Ready) GetFacts() *Facts {
	if x != nil {
		return x.Facts
	}
	return nil
}

// 周期心跳（节奏由注册应答下发）。
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint64                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Facts         *Facts                 `protobuf:"bytes,2,opt,name=facts,proto3" json:"facts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *Heartbeat) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *Heartbeat) GetFacts() *Facts {
	if x != nil {
		return x.Facts
	}
	return nil
}

// exec / install 的输出行（stdout/stderr 合并，逐行）。
type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *LogLine) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

// exec / install 终态。
type ExecResult struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Ok       bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ExitCode int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error    *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// 仅 install 成功时携带。
	Install       *InstallResult `protobuf:"bytes,4,opt,name=install,proto3" json:"install,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResult) Reset() {
	*x = ExecResult{}
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResult) ProtoMessage() {}

func (x *ExecResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResult.ProtoReflect.Descriptor instead.
func (*ExecResult) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ExecResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ExecResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecResult) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ExecResult) GetInstall() *InstallResult {
	if x != nil {
		return x.Install
	}
	return nil
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{14}
}

// 会话输出（原始字节，不保证是合法 UTF-8）。
type SessionData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionData) Reset() {
	*x = SessionData{}
	mi := &file_agent_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionData) ProtoMessage() {}

func (x *SessionData) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionData.ProtoReflect.Descriptor instead.
func (*SessionData) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *SessionData) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// 会话结束。
type SessionExit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionExit) Reset() {
	*x = SessionExit{}
	mi := &file_agent_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionExit) ProtoMessage() {}

func (x *SessionExit) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionExit.ProtoReflect.Descriptor instead.
func (*SessionExit) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *SessionExit) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *SessionExit) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// 结构化错误：控制面按 code 分支/重试，不解析字符串。
// 执行类：EXEC_TIMEOUT / EXEC_FAILED / CANCELLED / SCRIPT_WRITE_FAILED
// 装机类：INSTALL_PREFLIGHT_FAILED / INSTALL_STEP_FAILED / INSTALL_UNSUPPORTED_OS
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_agent_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{17}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

// 主机现状：注册（HTTP JSON，字段名同 json_name）、ready、心跳。
type Facts struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Hostname       string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	InternalIp     string                 `protobuf:"bytes,2,opt,name=internal_ip,json=internalIp,proto3" json:"internal_ip,omitempty"`
	Os             string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch           string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	Kernel         string                 `protobuf:"bytes,5,opt,name=kernel,proto3" json:"kernel,omitempty"`
	CpuCores       int32                  `protobuf:"varint,6,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemBytes       uint64                 `protobuf:"varint,7,opt,name=mem_bytes,json=memBytes,proto3" json:"mem_bytes,omitempty"`
	CpuUsedPercent float64                `protobuf:"fixed64,8,opt,name=cpu_used_percent,json=cpuUsedPercent,proto3" json:"cpu_used_percent,omitempty"`
	MemUsedPercent float64                `protobuf:"fixed64,9,opt,name=mem_used_percent,json=memUsedPercent,proto3" json:"mem_used_percent,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Facts) Reset() {
	*x = Facts{}
	mi := &file_agent_v1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Facts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Facts) ProtoMessage() {}

func (x *Facts) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Facts.ProtoReflect.Descriptor instead.
func (*Facts) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{18}
}

func (x *Facts) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Facts) GetInternalIp() string {
	if x != nil {
		return x.InternalIp
	}
	return ""
}

func (x *Facts) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Facts) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Facts) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *Facts) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *Facts) GetMemBytes() uint64 {
	if x != nil {
		return x.MemBytes
	}
	return 0
}

func (x *Facts) GetCpuUsedPercent() float64 {
	if x != nil {
		return x.CpuUsedPercent
	}
	return 0
}

func (x *Facts) GetMemUsedPercent() float64 {
	if x != nil {
		return x.MemUsedPercent
	}
	return 0
}

// 面板下发的结构化装机指令。agent 按 role 编排本机装机阶段。
type InstallSpec struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Role                 NodeRole               `protobuf:"varint,1,opt,name=role,proto3,enum=agent.v1.NodeRole" json:"role,omitempty"`
	K8SVersion           string                 `protobuf:"bytes,2,opt,name=k8s_version,json=k8sVersion,proto3" json:"k8s_version,omitempty"`                                 // 如 v1.35.7，空用 agent 默认
	PodCidr              string                 `protobuf:"bytes,3,opt,name=pod_cidr,json=podCidr,proto3" json:"pod_cidr,omitempty"`                                          // 如 10.244.0.0/16
	ServiceCidr          string                 `protobuf:"bytes,4,opt,name=service_cidr,json=serviceCidr,proto3" json:"service_cidr,omitempty"`                              // 如 10.96.0.0/12
	ImageRepository      string                 `protobuf:"bytes,5,opt,name=image_repository,json=imageRepository,proto3" json:"image_repository,omitempty"`                  // 镜像仓前缀，空用官方
	ControlPlaneEndpoint string                 `protobuf:"bytes,6,opt,name=control_plane_endpoint,json=controlPlaneEndpoint,proto3" json:"control_plane_endpoint,omitempty"` // VIP:6443 或外部 LB
	AdvertiseAddress     string                 `protobuf:"bytes,7,opt,name=advertise_address,json=advertiseAddress,proto3" json:"advertise_address,omitempty"`               // 本节点 apiserver 通告 IP
	CertSans             []string               `protobuf:"bytes,8,rep,name=cert_sans,json=certSans,proto3" json:"cert_sans,omitempty"`
	Vip                  *VipSpec               `protobuf:"bytes,9,opt,name=vip,proto3" json:"vip,omitempty"`            // 内置 kube-vip
	Cni                  *CniSpec               `protobuf:"bytes,10,opt,name=cni,proto3" json:"cni,omitempty"`           // 首 master 装 CNI
	Join                 *JoinSpec              `protobuf:"bytes,11,opt,name=join,proto3" json:"join,omitempty"`         // join-master / worker 用
	Artifact             *ArtifactSpec          `protobuf:"bytes,12,opt,name=artifact,proto3" json:"artifact,omitempty"` // 制品来源
	Addons               []string               `protobuf:"bytes,13,rep,name=addons,proto3" json:"addons,omitempty"`     // ingress-nginx / metrics-server / cert-manager
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *InstallSpec) Reset() {
	*x = InstallSpec{}
	mi := &file_agent_v1_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSpec) ProtoMessage() {}

func (x *InstallSpec) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSpec.ProtoReflect.Descriptor instead.
func (*InstallSpec) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{19}
}

func (x *InstallSpec) GetRole() NodeRole {
	if x != nil {
		return x.Role
	}
	return NodeRole_NODE_ROLE_UNSPECIFIED
}

func (x *InstallSpec) GetK8SVersion() string {
	if x != nil {
		return x.K8SVersion
	}
	return ""
}

func (x *InstallSpec) GetPodCidr() string {
	if x != nil {
		return x.PodCidr
	}
	return ""
}

func (x *InstallSpec) GetServiceCidr() string {
	if x != nil {
		return x.ServiceCidr
	}
	return ""
}

func (x *InstallSpec) GetImageRepository() string {
	if x != nil {
		return x.ImageRepository
	}
	return ""
}

func (x *InstallSpec) GetControlPlaneEndpoint() string {
	if x != nil {
		return x.ControlPlaneEndpoint
	}
	return ""
}

func (x *InstallSpec) GetAdvertiseAddress() string {
	if x != nil {
		return x.AdvertiseAddress
	}
	return ""
}

func (x *InstallSpec) GetCertSans() []string {
	if x != nil {
		return x.CertSans
	}
	return nil
}

func (x *InstallSpec) GetVip() *VipSpec {
	if x != nil {
		return x.Vip
	}
	return nil
}

func (x *InstallSpec) GetCni() *CniSpec {
	if x != nil {
		return x.Cni
	}
	return nil
}

func (x *InstallSpec) GetJoin() *JoinSpec {
	if x != nil {
		return x.Join
	}
	return nil
}

func (x *InstallSpec) GetArtifact() *ArtifactSpec {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *InstallSpec) GetAddons() []string {
	if x != nil {
		return x.Addons
	}
	return nil
}

// kube-vip 静态 Pod 参数（L2/ARP）。
type VipSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`     // VIP
	Interface     string                 `protobuf:"bytes,3,opt,name=interface,proto3" json:"interface,omitempty"` // 绑定网卡，空则自动探测
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`     // kube-vip 镜像 tag，空用内置默认
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VipSpec) Reset() {
	*x = VipSpec{}
	mi := &file_agent_v1_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VipSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VipSpec) ProtoMessage() {}

func (x *VipSpec) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VipSpec.ProtoReflect.Descriptor instead.
func (*VipSpec) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{20}
}

func (x *VipSpec) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *VipSpec) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *VipSpec) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *VipSpec) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type CniSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          CniType                `protobuf:"varint,1,opt,name=type,proto3,enum=agent.v1.CniType" json:"type,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // 如 1.16.5 / v3.29.1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CniSpec) Reset() {
	*x = CniSpec{}
	mi := &file_agent_v1_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CniSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CniSpec) ProtoMessage() {}

func (x *CniSpec) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CniSpec.ProtoReflect.Descriptor instead.
func (*CniSpec) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{21}
}

func (x *CniSpec) GetType() CniType {
	if x != nil {
		return x.Type
	}
	return CniType_CNI_TYPE_UNSPECIFIED
}

func (x *CniSpec) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// 加入集群所需凭据（由首 master 装机后回传）。
type JoinSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Token          string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	CaCertHash     string                 `protobuf:"bytes,2,opt,name=ca_cert_hash,json=caCertHash,proto3" json:"ca_cert_hash,omitempty"`           // sha256:...
	CertificateKey string                 `protobuf:"bytes,3,opt,name=certificate_key,json=certificateKey,proto3" json:"certificate_key,omitempty"` // 仅 join-master 用（2h 有效）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JoinSpec) Reset() {
	*x = JoinSpec{}
	mi := &file_agent_v1_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinSpec) ProtoMessage() {}

func (x *JoinSpec) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinSpec.ProtoReflect.Descriptor instead.
func (*JoinSpec) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{22}
}

func (x *JoinSpec) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *JoinSpec) GetCaCertHash() string {
	if x != nil {
		return x.CaCertHash
	}
	return ""
}

func (x *JoinSpec) GetCertificateKey() string {
	if x != nil {
		return x.CertificateKey
	}
	return ""
}

type ArtifactSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          ArtifactMode           `protobuf:"varint,1,opt,name=mode,proto3,enum=agent.v1.ArtifactMode" json:"mode,omitempty"`
	BundleUrl     string                 `protobuf:"bytes,2,opt,name=bundle_url,json=bundleUrl,proto3" json:"bundle_url,omitempty"`          // bundle：离线包地址（tar.gz 或 .parts.json 分卷清单）
	UseCnMirror   bool                   `protobuf:"varint,3,opt,name=use_cn_mirror,json=useCnMirror,proto3" json:"use_cn_mirror,omitempty"` // online：国内镜像源
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactSpec) Reset() {
	*x = ArtifactSpec{}
	mi := &file_agent_v1_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactSpec) ProtoMessage() {}

func (x *ArtifactSpec) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactSpec.ProtoReflect.Descriptor instead.
func (*ArtifactSpec) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{23}
}

func (x *ArtifactSpec) GetMode() ArtifactMode {
	if x != nil {
		return x.Mode
	}
	return ArtifactMode_ARTIFACT_MODE_UNSPECIFIED
}

func (x *ArtifactSpec) GetBundleUrl() string {
	if x != nil {
		return x.BundleUrl
	}
	return ""
}

func (x *ArtifactSpec) GetUseCnMirror() bool {
	if x != nil {
		return x.UseCnMirror
	}
	return false
}

// 装机终态的结构化输出。首 master 回传 join 凭据与 kubeconfig。
type InstallResult struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	JoinCommand          string                 `protobuf:"bytes,1,opt,name=join_command,json=joinCommand,proto3" json:"join_command,omitempty"`
	Token                string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	CaCertHash           string                 `protobuf:"bytes,3,opt,name=ca_cert_hash,json=caCertHash,proto3" json:"ca_cert_hash,omitempty"`
	CertificateKey       string                 `protobuf:"bytes,4,opt,name=certificate_key,json=certificateKey,proto3" json:"certificate_key,omitempty"`
	ControlPlaneEndpoint string                 `protobuf:"bytes,5,opt,name=control_plane_endpoint,json=controlPlaneEndpoint,proto3" json:"control_plane_endpoint,omitempty"`
	KubeconfigB64        string                 `protobuf:"bytes,6,opt,name=kubeconfig_b64,json=kubeconfigB64,proto3" json:"kubeconfig_b64,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *InstallResult) Reset() {
	*x = InstallResult{}
	mi := &file_agent_v1_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallResult) ProtoMessage() {}

func (x *InstallResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallResult.ProtoReflect.Descriptor instead.
func (*InstallResult) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{24}
}

func (x *InstallResult) GetJoinCommand() string {
	if x != nil {
		return x.JoinCommand
	}
	return ""
}

func (x *InstallResult) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *InstallResult) GetCaCertHash() string {
	if x != nil {
		return x.CaCertHash
	}
	return ""
}

func (x *InstallResult) GetCertificateKey() string {
	if x != nil {
		return x.CertificateKey
	}
	return ""
}

func (x *InstallResult) GetControlPlaneEndpoint() string {
	if x != nil {
		return x.ControlPlaneEndpoint
	}
	return ""
}

func (x *InstallResult) GetKubeconfigB64() string {
	if x != nil {
		return x.KubeconfigB64
	}
	return ""
}

var File_agent_v1_agent_proto protoreflect.FileDescriptor

const file_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14agent/v1/agent.proto\x12\bagent.v1\"\xec\x03\n" +
	"\vServerFrame\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12+\n" +
	"\x04exec\x18\n" +
	" \x01(\v2\x15.agent.v1.ExecRequestH\x00R\x04exec\x124\n" +
	"\ainstall\x18\v \x01(\v2\x18.agent.v1.InstallRequestH\x00R\ainstall\x121\n" +
	"\x06cancel\x18\f \x01(\v2\x17.agent.v1.CancelRequestH\x00R\x06cancel\x12$\n" +
	"\x04ping\x18\r \x01(\v2\x0e.agent.v1.PingH\x00R\x04ping\x12:\n" +
	"\fsession_open\x18\x14 \x01(\v2\x15.agent.v1.SessionOpenH\x00R\vsessionOpen\x12=\n" +
	"\rsession_stdin\x18\x15 \x01(\v2\x16.agent.v1.SessionStdinH\x00R\fsessionStdin\x12@\n" +
	"\x0esession_resize\x18\x16 \x01(\v2\x17.agent.v1.SessionResizeH\x00R\rsessionResize\x12=\n" +
	"\rsession_close\x18\x17 \x01(\v2\x16.agent.v1.SessionCloseH\x00R\fsessionCloseB\x06\n" +
	"\x04body\"\x86\x03\n" +
	"\n" +
	"AgentFrame\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12'\n" +
	"\x05ready\x18\n" +
	" \x01(\v2\x0f.agent.v1.ReadyH\x00R\x05ready\x123\n" +
	"\theartbeat\x18\v \x01(\v2\x13.agent.v1.HeartbeatH\x00R\theartbeat\x12%\n" +
	"\x03log\x18\f \x01(\v2\x11.agent.v1.LogLineH\x00R\x03log\x12.\n" +
	"\x06result\x18\r \x01(\v2\x14.agent.v1.ExecResultH\x00R\x06result\x12$\n" +
	"\x04pong\x18\x0e \x01(\v2\x0e.agent.v1.PongH\x00R\x04pong\x12:\n" +
	"\fsession_data\x18\x14 \x01(\v2\x15.agent.v1.SessionDataH\x00R\vsessionData\x12:\n" +
	"\fsession_exit\x18\x15 \x01(\v2\x15.agent.v1.SessionExitH\x00R\vsessionExitB\x06\n" +
	"\x04body\"D\n" +
	"\vExecRequest\x12\x16\n" +
	"\x06script\x18\x01 \x01(\tR\x06script\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\x03R\ttimeoutMs\";\n" +
	"\x0eInstallRequest\x12)\n" +
	"\x04spec\x18\x01 \x01(\v2\x15.agent.v1.InstallSpecR\x04spec\"\x0f\n" +
	"\rCancelRequest\"\x06\n" +
	"\x04Ping\"_\n" +
	"\vSessionOpen\x12\x16\n" +
	"\x06script\x18\x01 \x01(\tR\x06script\x12\x10\n" +
	"\x03tty\x18\x02 \x01(\bR\x03tty\x12\x12\n" +
	"\x04cols\x18\x03 \x01(\x05R\x04cols\x12\x12\n" +
	"\x04rows\x18\x04 \x01(\x05R\x04rows\"(\n" +
	"\fSessionStdin\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"7\n" +
	"\rSessionResize\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\x05R\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\x05R\x04rows\"\x0e\n" +
	"\fSessionClose\"l\n" +
	"\x05Ready\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12%\n" +
	"\x05facts\x18\x03 \x01(\v2\x0f.agent.v1.FactsR\x05facts\"K\n" +
	"\tHeartbeat\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\x12%\n" +
	"\x05facts\x18\x02 \x01(\v2\x0f.agent.v1.FactsR\x05facts\"\x1d\n" +
	"\aLogLine\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\"\x93\x01\n" +
	"\n" +
	"ExecResult\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12%\n" +
	"\x05error\x18\x03 \x01(\v2\x0f.agent.v1.ErrorR\x05error\x121\n" +
	"\ainstall\x18\x04 \x01(\v2\x17.agent.v1.InstallResultR\ainstall\"\x06\n" +
	"\x04Pong\"'\n" +
	"\vSessionData\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"Q\n" +
	"\vSessionExit\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12%\n" +
	"\x05error\x18\x02 \x01(\v2\x0f.agent.v1.ErrorR\x05error\"S\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\"\x8e\x02\n" +
	"\x05Facts\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1f\n" +
	"\vinternal_ip\x18\x02 \x01(\tR\n" +
	"internalIp\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x16\n" +
	"\x06kernel\x18\x05 \x01(\tR\x06kernel\x12\x1b\n" +
	"\tcpu_cores\x18\x06 \x01(\x05R\bcpuCores\x12\x1b\n" +
	"\tmem_bytes\x18\a \x01(\x04R\bmemBytes\x12(\n" +
	"\x10cpu_used_percent\x18\b \x01(\x01R\x0ecpuUsedPercent\x12(\n" +
	"\x10mem_used_percent\x18\t \x01(\x01R\x0ememUsedPercent\"\xfd\x03\n" +
	"\vInstallSpec\x12&\n" +
	"\x04role\x18\x01 \x01(\x0e2\x12.agent.v1.NodeRoleR\x04role\x12\x1f\n" +
	"\vk8s_version\x18\x02 \x01(\tR\n" +
	"k8sVersion\x12\x19\n" +
	"\bpod_cidr\x18\x03 \x01(\tR\apodCidr\x12!\n" +
	"\fservice_cidr\x18\x04 \x01(\tR\vserviceCidr\x12)\n" +
	"\x10image_repository\x18\x05 \x01(\tR\x0fimageRepository\x124\n" +
	"\x16control_plane_endpoint\x18\x06 \x01(\tR\x14controlPlaneEndpoint\x12+\n" +
	"\x11advertise_address\x18\a \x01(\tR\x10advertiseAddress\x12\x1b\n" +
	"\tcert_sans\x18\b \x03(\tR\bcertSans\x12#\n" +
	"\x03vip\x18\t \x01(\v2\x11.agent.v1.VipSpecR\x03vip\x12#\n" +
	"\x03cni\x18\n" +
	" \x01(\v2\x11.agent.v1.CniSpecR\x03cni\x12&\n" +
	"\x04join\x18\v \x01(\v2\x12.agent.v1.JoinSpecR\x04join\x122\n" +
	"\bartifact\x18\f \x01(\v2\x16.agent.v1.ArtifactSpecR\bartifact\x12\x16\n" +
	"\x06addons\x18\r \x03(\tR\x06addons\"u\n" +
	"\aVipSpec\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1c\n" +
	"\tinterface\x18\x03 \x01(\tR\tinterface\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"J\n" +
	"\aCniSpec\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.agent.v1.CniTypeR\x04type\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"k\n" +
	"\bJoinSpec\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12 \n" +
	"\fca_cert_hash\x18\x02 \x01(\tR\n" +
	"caCertHash\x12'\n" +
	"\x0fcertificate_key\x18\x03 \x01(\tR\x0ecertificateKey\"}\n" +
	"\fArtifactSpec\x12*\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x16.agent.v1.ArtifactModeR\x04mode\x12\x1d\n" +
	"\n" +
	"bundle_url\x18\x02 \x01(\tR\tbundleUrl\x12\"\n" +
	"\ruse_cn_mirror\x18\x03 \x01(\bR\vuseCnMirror\"\xf0\x01\n" +
	"\rInstallResult\x12!\n" +
	"\fjoin_command\x18\x01 \x01(\tR\vjoinCommand\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12 \n" +
	"\fca_cert_hash\x18\x03 \x01(\tR\n" +
	"caCertHash\x12'\n" +
	"\x0fcertificate_key\x18\x04 \x01(\tR\x0ecertificateKey\x124\n" +
	"\x16control_plane_endpoint\x18\x05 \x01(\tR\x14controlPlaneEndpoint\x12%\n" +
	"\x0ekubeconfig_b64\x18\x06 \x01(\tR\rkubeconfigB64*r\n" +
	"\bNodeRole\x12\x19\n" +
	"\x15NODE_ROLE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16NODE_ROLE_FIRST_MASTER\x10\x01\x12\x19\n" +
	"\x15NODE_ROLE_JOIN_MASTER\x10\x02\x12\x14\n" +
	"\x10NODE_ROLE_WORKER\x10\x03*M\n" +
	"\aCniType\x12\x18\n" +
	"\x14CNI_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCNI_TYPE_CILIUM\x10\x01\x12\x13\n" +
	"\x0fCNI_TYPE_CALICO\x10\x02*a\n" +
	"\fArtifactMode\x12\x1d\n" +
	"\x19ARTIFACT_MODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ARTIFACT_MODE_BUNDLE\x10\x01\x12\x18\n" +
	"\x14ARTIFACT_MODE_ONLINE\x10\x022N\n" +
	"\x10NodeAgentService\x12:\n" +
	"\aConnect\x12\x14.agent.v1.AgentFrame\x1a\x15.agent.v1.ServerFrame(\x010\x01B,Z*starport-panel/internal/pb/agentv1;agentv1b\x06proto3"

var (
	file_agent_v1_agent_proto_rawDescOnce sync.Once
	file_agent_v1_agent_proto_rawDescData []byte
)

func file_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)))
	})
	return file_agent_v1_agent_proto_rawDescData
}

var file_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_agent_v1_agent_proto_goTypes = []any{
	(NodeRole)(0),          // 0: agent.v1.NodeRole
	(CniType)(0),           // 1: agent.v1.CniType
	(ArtifactMode)(0),      // 2: agent.v1.ArtifactMode
	(*ServerFrame)(nil),    // 3: agent.v1.ServerFrame
	(*AgentFrame)(nil),     // 4: agent.v1.AgentFrame
	(*ExecRequest)(nil),    // 5: agent.v1.ExecRequest
	(*InstallRequest)(nil), // 6: agent.v1.InstallRequest
	(*CancelRequest)(nil),  // 7: agent.v1.CancelRequest
	(*Ping)(nil),           // 8: agent.v1.Ping
	(*SessionOpen)(nil),    // 9: agent.v1.SessionOpen
	(*SessionStdin)(nil),   // 10: agent.v1.SessionStdin
	(*SessionResize)(nil),  // 11: agent.v1.SessionResize
	(*SessionClose)(nil),   // 12: agent.v1.SessionClose
	(*Ready)(nil),          // 13: agent.v1.Ready
	(*Heartbeat)(nil),      // 14: agent.v1.Heartbeat
	(*LogLine)(nil),        // 15: agent.v1.LogLine
	(*ExecResult)(nil),     // 16: agent.v1.ExecResult
	(*Pong)(nil),           // 17: agent.v1.Pong
	(*SessionData)(nil),    // 18: agent.v1.SessionData
	(*SessionExit)(nil),    // 19: agent.v1.SessionExit
	(*Error)(nil),          // 20: agent.v1.Error
	(*Facts)(nil),          // 21: agent.v1.Facts
	(*InstallSpec)(nil),    // 22: agent.v1.InstallSpec
	(*VipSpec)(nil),        // 23: agent.v1.VipSpec
	(*CniSpec)(nil),        // 24: agent.v1.CniSpec
	(*JoinSpec)(nil),       // 25: agent.v1.JoinSpec
	(*ArtifactSpec)(nil),   // 26: agent.v1.ArtifactSpec
	(*InstallResult)(nil),  // 27: agent.v1.InstallResult
}
var file_agent_v1_agent_proto_depIdxs = []int32{
	5,  // 0: agent.v1.ServerFrame.exec:type_name -> agent.v1.ExecRequest
	6,  // 1: agent.v1.ServerFrame.install:type_name -> agent.v1.InstallRequest
	7,  // 2: agent.v1.ServerFrame.cancel:type_name -> agent.v1.CancelRequest
	8,  // 3: agent.v1.ServerFrame.ping:type_name -> agent.v1.Ping
	9,  // 4: agent.v1.ServerFrame.session_open:type_name -> agent.v1.SessionOpen
	10, // 5: agent.v1.ServerFrame.session_stdin:type_name -> agent.v1.SessionStdin
	11, // 6: agent.v1.ServerFrame.session_resize:type_name -> agent.v1.SessionResize
	12, // 7: agent.v1.ServerFrame.session_close:type_name -> agent.v1.SessionClose
	13, // 8: agent.v1.AgentFrame.ready:type_name -> agent.v1.Ready
	14, // 9: agent.v1.AgentFrame.heartbeat:type_name -> agent.v1.Heartbeat
	15, // 10: agent.v1.AgentFrame.log:type_name -> agent.v1.LogLine
	16, // 11: agent.v1.AgentFrame.result:type_name -> agent.v1.ExecResult
	17, // 12: agent.v1.AgentFrame.pong:type_name -> agent.v1.Pong
	18, // 13: agent.v1.AgentFrame.session_data:type_name -> agent.v1.SessionData
	19, // 14: agent.v1.AgentFrame.session_exit:type_name -> agent.v1.SessionExit
	22, // 15: agent.v1.InstallRequest.spec:type_name -> agent.v1.InstallSpec
	21, // 16: agent.v1.Ready.facts:type_name -> agent.v1.Facts
	21, // 17: agent.v1.Heartbeat.facts:type_name -> agent.v1.Facts
	20, // 18: agent.v1.ExecResult.error:type_name -> agent.v1.Error
	27, // 19: agent.v1.ExecResult.install:type_name -> agent.v1.InstallResult
	20, // 20: agent.v1.SessionExit.error:type_name -> agent.v1.Error
	0,  // 21: agent.v1.InstallSpec.role:type_name -> agent.v1.NodeRole
	23, // 22: agent.v1.InstallSpec.vip:type_name -> agent.v1.VipSpec
	24, // 23: agent.v1.InstallSpec.cni:type_name -> agent.v1.CniSpec
	25, // 24: agent.v1.InstallSpec.join:type_name -> agent.v1.JoinSpec
	26, // 25: agent.v1.InstallSpec.artifact:type_name -> agent.v1.ArtifactSpec
	1,  // 26: agent.v1.CniSpec.type:type_name -> agent.v1.CniType
	2,  // 27: agent.v1.ArtifactSpec.mode:type_name -> agent.v1.ArtifactMode
	4,  // 28: agent.v1.NodeAgentService.Connect:input_type -> agent.v1.AgentFrame
	3,  // 29: agent.v1.NodeAgentService.Connect:output_type -> agent.v1.ServerFrame
	29, // [29:30] is the sub-list for method output_type
	28, // [28:29] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_agent_v1_agent_proto_init() }
func file_agent_v1_agent_proto_init() {
	if File_agent_v1_agent_proto != nil {
		return
	}
	file_agent_v1_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*ServerFrame_Exec)(nil),
		(*ServerFrame_Install)(nil),
		(*ServerFrame_Cancel)(nil),
		(*ServerFrame_Ping)(nil),
		(*ServerFrame_SessionOpen)(nil),
		(*ServerFrame_SessionStdin)(nil),
		(*ServerFrame_SessionResize)(nil),
		(*ServerFrame_SessionClose)(nil),
	}
	file_agent_v1_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*AgentFrame_Ready)(nil),
		(*AgentFrame_Heartbeat)(nil),
		(*AgentFrame_Log)(nil),
		(*AgentFrame_Result)(nil),
		(*AgentFrame_Pong)(nil),
		(*AgentFrame_SessionData)(nil),
		(*AgentFrame_SessionExit)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_agent_v1_agent_proto = out.File
	file_agent_v1_agent_proto_goTypes = nil
	file_agent_v1_agent_proto_depIdxs = nil
}
