// starport-agent（节点侧）↔ starport-panel（控制面）契约，唯一事实来源。
//
// 拓扑（Nacos 2.x 风格）：agent 主动呼出、单条 gRPC 双向流长连；面板沿同一条流反向下发指令。
// 节点上不监听端口、不保管 SSH 凭证，天然穿 NAT。
//
//   1. 引导注册走 HTTP：POST {panel}/api/v1/agents/register（凭引导令牌），
//      应答里下发 nodeId / agentToken / grpcEndpoints；agent 据此连 gRPC 端口。
//   2. 长连：NodeAgentService.Connect 双向流。metadata 携带
//        x-starport-agent-token / x-starport-node-id / x-starport-agent-version
//      令牌无效返回 UNAUTHENTICATED，agent 清本地身份重新注册。
//
// 生成物：internal/pb/agentv1（`make proto` / `buf generate`，产物入库）。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: agent/v1/agent.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeAgentService_Connect_FullMethodName = "/agent.v1.NodeAgentService/Connect"
)

// NodeAgentServiceClient is the client API for NodeAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeAgentServiceClient interface {
	// 呼出长连：agent 发起，双向复用。首帧必须是 Ready。
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentFrame, ServerFrame], error)
}

type nodeAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeAgentServiceClient(cc grpc.ClientConnInterface) NodeAgentServiceClient {
	return &nodeAgentServiceClient{cc}
}

func (c *nodeAgentServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentFrame, ServerFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeAgentService_ServiceDesc.Streams[0], NodeAgentService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentFrame, ServerFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgentService_ConnectClient = grpc.BidiStreamingClient[AgentFrame, ServerFrame]

// NodeAgentServiceServer is the server API for NodeAgentService service.
// All implementations must embed UnimplementedNodeAgentServiceServer
// for forward compatibility.
type NodeAgentServiceServer interface {
	// 呼出长连：agent 发起，双向复用。首帧必须是 Ready。
	Connect(grpc.BidiStreamingServer[AgentFrame, ServerFrame]) error
	mustEmbedUnimplementedNodeAgentServiceServer()
}

// UnimplementedNodeAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeAgentServiceServer struct{}

func (UnimplementedNodeAgentServiceServer) Connect(grpc.BidiStreamingServer[AgentFrame, ServerFrame]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedNodeAgentServiceServer) mustEmbedUnimplementedNodeAgentServiceServer() {}
func (UnimplementedNodeAgentServiceServer) testEmbeddedByValue()                          {}

// UnsafeNodeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeAgentServiceServer will
// result in compilation errors.
type UnsafeNodeAgentServiceServer interface {
	mustEmbedUnimplementedNodeAgentServiceServer()
}

func RegisterNodeAgentServiceServer(s grpc.ServiceRegistrar, srv NodeAgentServiceServer) {
	// If the following call panics, it indicates UnimplementedNodeAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeAgentService_ServiceDesc, srv)
}

func _NodeAgentService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeAgentServiceServer).Connect(&grpc.GenericServerStream[AgentFrame, ServerFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgentService_ConnectServer = grpc.BidiStreamingServer[AgentFrame, ServerFrame]

// NodeAgentService_ServiceDesc is the grpc.ServiceDesc for NodeAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.v1.NodeAgentService",
	HandlerType: (*NodeAgentServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _NodeAgentService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agent/v1/agent.proto",
}
